export const COUPONS_GET_REQUEST = 'COUPONS_GET_REQUEST'
 export const COUPONS_GET_SUCCESS = 'COUPONS_GET_SUCCESS'
 export const COUPONS_GET_FAIL = 'COUPONS_GET_FAIL'

 export const COUPON_CREATE_REQUEST = 'COUPON_CREATE_REQUEST'
 export const COUPON_CREATE_SUCCESS = 'COUPON_CREATE_SUCCESS'
 export const COUPON_CREATE_FAIL = 'COUPON_CREATE_FAIL'
 export const COUPON_CREATE_RESET = 'COUPON_CREATE_RESET'

 export const COUPON_DELETE_REQUEST = 'COUPON_DELETE_REQUEST'
 export const COUPON_DELETE_SUCCESS = 'COUPON_DELETE_SUCCESS'
 export const COUPON_DELETE_FAIL = 'COUPON_DELETE_FAIL'
 export const COUPON_DELETE_RESET = 'COUPON_DELETE_RESET'